namespace Lg2.Native
{
    [NativeTypeName("int")]
    public enum git_checkout_strategy_t : uint
    {
        GIT_CHECKOUT_SAFE = 0,
        GIT_CHECKOUT_FORCE = (1U << 1),
        GIT_CHECKOUT_RECREATE_MISSING = (1U << 2),
        GIT_CHECKOUT_ALLOW_CONFLICTS = (1U << 4),
        GIT_CHECKOUT_REMOVE_UNTRACKED = (1U << 5),
        GIT_CHECKOUT_REMOVE_IGNORED = (1U << 6),
        GIT_CHECKOUT_UPDATE_ONLY = (1U << 7),
        GIT_CHECKOUT_DONT_UPDATE_INDEX = (1U << 8),
        GIT_CHECKOUT_NO_REFRESH = (1U << 9),
        GIT_CHECKOUT_SKIP_UNMERGED = (1U << 10),
        GIT_CHECKOUT_USE_OURS = (1U << 11),
        GIT_CHECKOUT_USE_THEIRS = (1U << 12),
        GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH = (1U << 13),
        GIT_CHECKOUT_SKIP_LOCKED_DIRECTORIES = (1U << 18),
        GIT_CHECKOUT_DONT_OVERWRITE_IGNORED = (1U << 19),
        GIT_CHECKOUT_CONFLICT_STYLE_MERGE = (1U << 20),
        GIT_CHECKOUT_CONFLICT_STYLE_DIFF3 = (1U << 21),
        GIT_CHECKOUT_DONT_REMOVE_EXISTING = (1U << 22),
        GIT_CHECKOUT_DONT_WRITE_INDEX = (1U << 23),
        GIT_CHECKOUT_DRY_RUN = (1U << 24),
        GIT_CHECKOUT_CONFLICT_STYLE_ZDIFF3 = (1U << 25),
        GIT_CHECKOUT_NONE = (1U << 30),
        GIT_CHECKOUT_UPDATE_SUBMODULES = (1U << 16),
        GIT_CHECKOUT_UPDATE_SUBMODULES_IF_CHANGED = (1U << 17),
    }
}
