namespace Lg2.Native
{
    [NativeTypeName("int")]
    public enum git_diff_option_t : uint
    {
        GIT_DIFF_NORMAL = 0,
        GIT_DIFF_REVERSE = (1U << 0),
        GIT_DIFF_INCLUDE_IGNORED = (1U << 1),
        GIT_DIFF_RECURSE_IGNORED_DIRS = (1U << 2),
        GIT_DIFF_INCLUDE_UNTRACKED = (1U << 3),
        GIT_DIFF_RECURSE_UNTRACKED_DIRS = (1U << 4),
        GIT_DIFF_INCLUDE_UNMODIFIED = (1U << 5),
        GIT_DIFF_INCLUDE_TYPECHANGE = (1U << 6),
        GIT_DIFF_INCLUDE_TYPECHANGE_TREES = (1U << 7),
        GIT_DIFF_IGNORE_FILEMODE = (1U << 8),
        GIT_DIFF_IGNORE_SUBMODULES = (1U << 9),
        GIT_DIFF_IGNORE_CASE = (1U << 10),
        GIT_DIFF_INCLUDE_CASECHANGE = (1U << 11),
        GIT_DIFF_DISABLE_PATHSPEC_MATCH = (1U << 12),
        GIT_DIFF_SKIP_BINARY_CHECK = (1U << 13),
        GIT_DIFF_ENABLE_FAST_UNTRACKED_DIRS = (1U << 14),
        GIT_DIFF_UPDATE_INDEX = (1U << 15),
        GIT_DIFF_INCLUDE_UNREADABLE = (1U << 16),
        GIT_DIFF_INCLUDE_UNREADABLE_AS_UNTRACKED = (1U << 17),
        GIT_DIFF_INDENT_HEURISTIC = (1U << 18),
        GIT_DIFF_IGNORE_BLANK_LINES = (1U << 19),
        GIT_DIFF_FORCE_TEXT = (1U << 20),
        GIT_DIFF_FORCE_BINARY = (1U << 21),
        GIT_DIFF_IGNORE_WHITESPACE = (1U << 22),
        GIT_DIFF_IGNORE_WHITESPACE_CHANGE = (1U << 23),
        GIT_DIFF_IGNORE_WHITESPACE_EOL = (1U << 24),
        GIT_DIFF_SHOW_UNTRACKED_CONTENT = (1U << 25),
        GIT_DIFF_SHOW_UNMODIFIED = (1U << 26),
        GIT_DIFF_PATIENCE = (1U << 28),
        GIT_DIFF_MINIMAL = (1U << 29),
        GIT_DIFF_SHOW_BINARY = (1U << 30),
    }
}
