namespace Lg2.Native
{
    [NativeTypeName("int")]
    public enum git_status_opt_t : uint
    {
        GIT_STATUS_OPT_INCLUDE_UNTRACKED = (1U << 0),
        GIT_STATUS_OPT_INCLUDE_IGNORED = (1U << 1),
        GIT_STATUS_OPT_INCLUDE_UNMODIFIED = (1U << 2),
        GIT_STATUS_OPT_EXCLUDE_SUBMODULES = (1U << 3),
        GIT_STATUS_OPT_RECURSE_UNTRACKED_DIRS = (1U << 4),
        GIT_STATUS_OPT_DISABLE_PATHSPEC_MATCH = (1U << 5),
        GIT_STATUS_OPT_RECURSE_IGNORED_DIRS = (1U << 6),
        GIT_STATUS_OPT_RENAMES_HEAD_TO_INDEX = (1U << 7),
        GIT_STATUS_OPT_RENAMES_INDEX_TO_WORKDIR = (1U << 8),
        GIT_STATUS_OPT_SORT_CASE_SENSITIVELY = (1U << 9),
        GIT_STATUS_OPT_SORT_CASE_INSENSITIVELY = (1U << 10),
        GIT_STATUS_OPT_RENAMES_FROM_REWRITES = (1U << 11),
        GIT_STATUS_OPT_NO_REFRESH = (1U << 12),
        GIT_STATUS_OPT_UPDATE_INDEX = (1U << 13),
        GIT_STATUS_OPT_INCLUDE_UNREADABLE = (1U << 14),
        GIT_STATUS_OPT_INCLUDE_UNREADABLE_AS_UNTRACKED = (1U << 15),
    }
}
