namespace Lg2.Native
{
    [NativeTypeName("int")]
    public enum git_diff_find_t : uint
    {
        GIT_DIFF_FIND_BY_CONFIG = 0,
        GIT_DIFF_FIND_RENAMES = (1U << 0),
        GIT_DIFF_FIND_RENAMES_FROM_REWRITES = (1U << 1),
        GIT_DIFF_FIND_COPIES = (1U << 2),
        GIT_DIFF_FIND_COPIES_FROM_UNMODIFIED = (1U << 3),
        GIT_DIFF_FIND_REWRITES = (1U << 4),
        GIT_DIFF_BREAK_REWRITES = (1U << 5),
        GIT_DIFF_FIND_AND_BREAK_REWRITES = (GIT_DIFF_FIND_REWRITES | GIT_DIFF_BREAK_REWRITES),
        GIT_DIFF_FIND_FOR_UNTRACKED = (1U << 6),
        GIT_DIFF_FIND_ALL = (0x0ff),
        GIT_DIFF_FIND_IGNORE_LEADING_WHITESPACE = 0,
        GIT_DIFF_FIND_IGNORE_WHITESPACE = (1U << 12),
        GIT_DIFF_FIND_DONT_IGNORE_WHITESPACE = (1U << 13),
        GIT_DIFF_FIND_EXACT_MATCH_ONLY = (1U << 14),
        GIT_DIFF_BREAK_REWRITES_FOR_RENAMES_ONLY = (1U << 15),
        GIT_DIFF_FIND_REMOVE_UNMODIFIED = (1U << 16),
    }
}
