namespace Lg2.Native
{
    public enum git_repository_item_t
    {
        GIT_REPOSITORY_ITEM_GITDIR,
        GIT_REPOSITORY_ITEM_WORKDIR,
        GIT_REPOSITORY_ITEM_COMMONDIR,
        GIT_REPOSITORY_ITEM_INDEX,
        GIT_REPOSITORY_ITEM_OBJECTS,
        GIT_REPOSITORY_ITEM_REFS,
        GIT_REPOSITORY_ITEM_PACKED_REFS,
        GIT_REPOSITORY_ITEM_REMOTES,
        GIT_REPOSITORY_ITEM_CONFIG,
        GIT_REPOSITORY_ITEM_INFO,
        GIT_REPOSITORY_ITEM_HOOKS,
        GIT_REPOSITORY_ITEM_LOGS,
        GIT_REPOSITORY_ITEM_MODULES,
        GIT_REPOSITORY_ITEM_WORKTREES,
        GIT_REPOSITORY_ITEM_WORKTREE_CONFIG,
        GIT_REPOSITORY_ITEM__LAST,
    }
}
